
version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    image: 455649620401.dkr.ecr.ap-northeast-1.amazonaws.com/apple-site
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
