# Generated by Django 3.1.3 on 2020-11-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentications', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Out_Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('display_size', models.DecimalField(decimal_places=1, max_digits=2)),
                ('device_size', models.DecimalField(decimal_places=1, max_digits=2)),
                ('home_button', models.BooleanField(default=True)),
                ('release_date', models.CharField(max_length=50)),
                ('in_camera', models.CharField(max_length=50)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.authentication')),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.capacity', verbose_name='GB')),
                ('color', models.ManyToManyField(to='apple.Color')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.cpu')),
                ('out_camera', models.ManyToManyField(to='apple.Out_Camera')),
            ],
        ),
    ]
