# Generated by Django 3.1.3 on 2020-11-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='capacities',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='device',
            name='capacity',
        ),
        migrations.AddField(
            model_name='device',
            name='capacity',
            field=models.ManyToManyField(to='apple.Capacity'),
        ),
    ]
