# Generated by Django 3.1.3 on 2020-11-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_auto_20201109_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='home_button',
            field=models.CharField(max_length=3),
        ),
    ]
