# Generated by Django 3.1.3 on 2020-11-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0004_auto_20201109_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='DeviceModel',
        ),
        migrations.AlterModelTable(
            name='devicemodel',
            table='device',
        ),
    ]
