# Generated by Django 3.1.3 on 2020-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0005_auto_20201111_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='device_size',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
