# Generated by Django 3.1.3 on 2020-11-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0007_auto_20201111_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='device_size',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='gram',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
